### PR TITLE
add forgot password page

### LINKED ISSUE #3: Add Forgot Password Page
We need to add forgot password page as there is no page is rendering when we click on forgot password option.

@abhijivani3001 I would like to work on this issue , I can design and develop the page according to your current existing theme .
requesting you to kindly assign this issue to me and add hactoberfest tag on the issue.

### PR DESCRIPTION
**Pull request by Karan1962**
Fixes #3 

Added forgot password page UI as followed 

https://github.com/user-attachments/assets/98692945-398a-43d0-81db-b492496cf6c5

monkeytype(2)
monkeytype

@abhijivani3001 kindly suggest if any changes required.

### CODE REVIEW

**Comment by abhijivani3001** [comment]
@Karan1962 overall it was good, but maintain the vertical alignment proper.. it should be at the middle of the page.

**Comment by Karan1962** [comment]
@abhijivani3001 noted !

**Comment by Karan1962** [comment]
center
center2


@abhijivani3001 If any other changes required please let me know !

**Comment by abhijivani3001** [comment]
Following errors occurred in deployment. Please fix it.

[11:08:18.667] Running build in Washington, D.C., USA (East) – iad1
[11:08:18.799] Cloning github.com/abhijivani3001/multi-monkey (Branch: newPage, Commit: c8ab098)
[11:08:19.048] Cloning completed: 248.249ms
[11:08:21.185] Restored build cache from previous deployment (5eGQrRnzfWYeSKviKUjrkBhHNzsC)
[11:08:21.254] Running "vercel build"
[11:08:21.716] Vercel CLI 37.12.0
[11:08:22.359] Installing dependencies...
[11:08:23.467] 
[11:08:23.467] up to date in 886ms
[11:08:23.467] 
[11:08:23.467] 70 packages are looking for funding
[11:08:23.468]   run `npm fund` for details
[11:08:23.480] Running "npm run build"
[11:08:23.617] 
[11:08:23.617] > frontend@0.0.0 build
[11:08:23.617] > tsc && vite build
[11:08:23.618] 
[11:08:28.018] src/pages/ForgotPassword.tsx(34,36): error TS6133: 'email' is declared but its value is never read.
[11:08:28.045] Error: Command "npm run build" exited with 2
[11:08:28.523]

**Review by abhijivani3001 — APPROVED** [review]
done.

**Pull request merged**
